CREATE TABLE IF NOT EXISTS wallets (
    id VARCHAR(100) PRIMARY KEY NOT NULL,
    owned_by VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    disabled_at TIMESTAMP WITH TIME ZONE,
    enabled_at TIMESTAMP WITH TIME ZONE,
    balance DECIMAL(18, 2) NOT NULL DEFAULT 0
);
