// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	wallet "github.com/defryheryanto/mini-wallet/internal/wallet"
	mock "github.com/stretchr/testify/mock"
)

// WalletIService is an autogenerated mock type for the WalletIService type
type WalletIService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, params
func (_m *WalletIService) Create(ctx context.Context, params *wallet.CreateWalletParams) error {
	ret := _m.Called(ctx, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *wallet.CreateWalletParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnableWallet provides a mock function with given fields: ctx, customerXid
func (_m *WalletIService) EnableWallet(ctx context.Context, customerXid string) (*wallet.Wallet, error) {
	ret := _m.Called(ctx, customerXid)

	var r0 *wallet.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*wallet.Wallet, error)); ok {
		return rf(ctx, customerXid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *wallet.Wallet); ok {
		r0 = rf(ctx, customerXid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerXid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletByXid provides a mock function with given fields: ctx, customerXid
func (_m *WalletIService) GetWalletByXid(ctx context.Context, customerXid string) (*wallet.Wallet, error) {
	ret := _m.Called(ctx, customerXid)

	var r0 *wallet.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*wallet.Wallet, error)); ok {
		return rf(ctx, customerXid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *wallet.Wallet); ok {
		r0 = rf(ctx, customerXid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerXid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWalletIService interface {
	mock.TestingT
	Cleanup(func())
}

// NewWalletIService creates a new instance of WalletIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWalletIService(t mockConstructorTestingTNewWalletIService) *WalletIService {
	mock := &WalletIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
