name: CI
on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps: 
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19' 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Unit Tests
        run: | 
          go test -v ./...